config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "admin/dashboard#index"
  get "legal", to: "pages#legal"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  devise_for :users

  get "/api-docs", to: "swagger_ui#index"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Validation "à blanc" (sans commande associée)
      post "validation", to: "validations#validate"

      # Commandes
      resources :orders, only: [ :create, :update ]

      # Catalogue produits (lecture seule)
      resources :products, only: [ :index, :show ], param: :c10

      # Recherche de circle_values (pour la enrichir les order_lines des commandes)
      post "search_circle_values", to: "circle_values#search"
    end
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <%= notice %>
    <a class="ms-3 cursor-pointer" data-bs-dismiss="alert" aria-label="Close">
      <%= svg_tag('pictos/close') %>
    </a>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <%= alert %>
    <a class="ms-3 cursor-pointer" data-bs-dismiss="alert" aria-label="Close">
      <%= svg_tag('pictos/close') %>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="<%= yield(:footer_classes)%> footer d-flex justify-content-between align-items-center">
  <div class="footer-links">
  </div>
  <div class="footer-copyright d-flex flex-column">
    © 2018 Your Domain
    <%= link_to legal_path do %>
      Mentions légales
    <% end %>
    <%= link_to "https://www.mihivai.com/", target: "_blank" do %>
      Site réalisé par Mihivai
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="<%= yield(:navbar_classes)%>">
  <div class="navbar">
    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag "logo.png" %><span class="title d-none d-md-block">Mihivai</span>
    <% end %>

    <div class='d-flex align-items-center gap-3'>
      <div class="nav-item dropdown">
        <div class='avatar cursor-pointer d-none d-md-flex justify-content-center align-items-center' id="navbarDropdown" aria-haspopup="true" aria-expanded="false" data-bs-toggle="dropdown">
          <%= svg_tag('pictos/avatar') %>
        </div>

        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to 'Se déconnecter', destroy_user_session_path, class: 'dropdown-item', data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to 'Se connecter', new_user_session_path, class: 'dropdown-item'  %>
          <% end %>
        </div>
      </div>

    </div>
  </div>

  <div style="height: 70px;"></div>
</div>